// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type NetworkInitParameters_2 struct {

	// (Set of String) Additional IPs to assign to the Server.
	// Additional IPs to assign to the Server.
	// +listType=set
	AliasIps []*string `json:"aliasIps,omitempty" tf:"alias_ips,omitempty"`

	// (String) IP to assign to the Server.
	// IP to assign to the Server.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) ID of the Subnet to attach the Server to. Required if network_id is not set.
	// ID of the Subnet to attach the Server to. Required if `network_id` is not set.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/network/v1alpha1.Subnet
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type NetworkObservation_2 struct {

	// (Set of String) Additional IPs to assign to the Server.
	// Additional IPs to assign to the Server.
	// +listType=set
	AliasIps []*string `json:"aliasIps,omitempty" tf:"alias_ips,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) IP to assign to the Server.
	// IP to assign to the Server.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) MAC address of the Server on the Network.
	// MAC address of the Server on the Network.
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// (Number) ID of the Network to attach the Server to. Using subnet_id is preferred. Required if subnet_id is not set. If subnet_id or ip are not set, the Server will be attached to the last subnet (ordered by ip_range).
	// ID of the Network to attach the Server to. Using `subnet_id` is preferred. Required if `subnet_id` is not set. If `subnet_id` or `ip` are not set, the Server will be attached to the last subnet (ordered by `ip_range`).
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (Number) ID of the Server.
	// ID of the Server.
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// (String) ID of the Subnet to attach the Server to. Required if network_id is not set.
	// ID of the Subnet to attach the Server to. Required if `network_id` is not set.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type NetworkParameters_2 struct {

	// (Set of String) Additional IPs to assign to the Server.
	// Additional IPs to assign to the Server.
	// +kubebuilder:validation:Optional
	// +listType=set
	AliasIps []*string `json:"aliasIps,omitempty" tf:"alias_ips,omitempty"`

	// (String) IP to assign to the Server.
	// IP to assign to the Server.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) ID of the Network to attach the Server to. Using subnet_id is preferred. Required if subnet_id is not set. If subnet_id or ip are not set, the Server will be attached to the last subnet (ordered by ip_range).
	// ID of the Network to attach the Server to. Using `subnet_id` is preferred. Required if `subnet_id` is not set. If `subnet_id` or `ip` are not set, the Server will be attached to the last subnet (ordered by `ip_range`).
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (Number) ID of the Server.
	// ID of the Server.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Reference to a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDRef *v1.NamespacedReference `json:"serverIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDSelector *v1.NamespacedSelector `json:"serverIdSelector,omitempty" tf:"-"`

	// (String) ID of the Subnet to attach the Server to. Required if network_id is not set.
	// ID of the Subnet to attach the Server to. Required if `network_id` is not set.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

// NetworkSpec defines the desired state of Network
type NetworkSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            NetworkParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInitParameters_2 `json:"initProvider,omitempty"`
}

// NetworkStatus defines the observed state of Network.
type NetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Network is the Schema for the Networks API. Manage the attachment of a Server in a Network in the Hetzner Cloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,hetzner}
type Network struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              NetworkSpec   `json:"spec"`
	Status            NetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkList contains a list of Networks
type NetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Network `json:"items"`
}

// Repository type metadata.
var (
	Network_Kind             = "Network"
	Network_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Network_Kind}.String()
	Network_KindAPIVersion   = Network_Kind + "." + CRDGroupVersion.String()
	Network_GroupVersionKind = CRDGroupVersion.WithKind(Network_Kind)
)

func init() {
	SchemeBuilder.Register(&Network{}, &NetworkList{})
}
