apiVersion: network.hetzner.m.crossplane.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: sample_certificate
  name: sample-certificate
  namespace: crossplane-system
spec:
  forProvider:
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDMDCCAhigAwIBAgIIJgROscP8RRUwDQYJKoZIhvcNAQELBQAwIDEeMBwGA1UE
      ...
      TKS8gQ==
      -----END CERTIFICATE-----
    labels:
      label_1: value_1
      label_2: value_2
    name: test-certificate-%d
    privateKeySecretRef:
      key: example-key
      name: example-secret
