apiVersion: network.hetzner.m.crossplane.io/v1alpha1
kind: ManagedCertificate
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/managedcertificate
  labels:
    testing.upbound.io/example-name: managed_cert
  name: managed-cert
  namespace: crossplane-system
spec:
  forProvider:
    domainNames:
    - '*.example.com'
    - example.com
    labels:
      label_1: value_1
      label_2: value_2
    name: managed_cert
