apiVersion: network.hetzner.m.crossplane.io/v1alpha1
kind: Subnet
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnet
  labels:
    testing.upbound.io/example-name: foonet
  name: foonet
  namespace: crossplane-system
spec:
  forProvider:
    ipRange: 10.0.1.0/24
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mynet
    networkZone: eu-central
    type: cloud

---

apiVersion: network.hetzner.m.crossplane.io/v1alpha1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/subnet
  labels:
    testing.upbound.io/example-name: mynet
  name: mynet
  namespace: crossplane-system
spec:
  forProvider:
    ipRange: 10.0.0.0/8
    name: my-net
