// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BalancerNetworkInitParameters struct {

	// (Boolean) Wether the Load Balancer public interface is enabled. Default is true.
	// Wether the Load Balancer public interface is enabled. Default is `true`.
	EnablePublicInterface *bool `json:"enablePublicInterface,omitempty" tf:"enable_public_interface,omitempty"`

	// (String) IP to assign to the Load Balancer.
	// IP to assign to the Load Balancer.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) ID of the Subnet to attach the Load Balancer to. Required if network_id is not set.
	// ID of the Subnet to attach the Load Balancer to. Required if `network_id` is not set.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/network/v1alpha1.Subnet
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type BalancerNetworkObservation struct {

	// (Boolean) Wether the Load Balancer public interface is enabled. Default is true.
	// Wether the Load Balancer public interface is enabled. Default is `true`.
	EnablePublicInterface *bool `json:"enablePublicInterface,omitempty" tf:"enable_public_interface,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) IP to assign to the Load Balancer.
	// IP to assign to the Load Balancer.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) ID of the Load Balancer.
	// ID of the Load Balancer.
	LoadBalancerID *float64 `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// (Number) ID of the Network to attach the Load Balancer to. Using subnet_id is preferred. Required if subnet_id is not set. If subnet_id or ip are not set, the Load Balancer will be attached to the last subnet (ordered by ip_range).
	// ID of the Network to attach the Load Balancer to. Using `subnet_id` is preferred. Required if `subnet_id` is not set. If `subnet_id` or `ip` are not set, the Load Balancer will be attached to the last subnet (ordered by `ip_range`).
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) ID of the Subnet to attach the Load Balancer to. Required if network_id is not set.
	// ID of the Subnet to attach the Load Balancer to. Required if `network_id` is not set.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`
}

type BalancerNetworkParameters struct {

	// (Boolean) Wether the Load Balancer public interface is enabled. Default is true.
	// Wether the Load Balancer public interface is enabled. Default is `true`.
	// +kubebuilder:validation:Optional
	EnablePublicInterface *bool `json:"enablePublicInterface,omitempty" tf:"enable_public_interface,omitempty"`

	// (String) IP to assign to the Load Balancer.
	// IP to assign to the Load Balancer.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) ID of the Load Balancer.
	// ID of the Load Balancer.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/loadbalancer/v1alpha1.Balancer
	// +kubebuilder:validation:Optional
	LoadBalancerID *float64 `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// Reference to a Balancer in loadbalancer to populate loadBalancerId.
	// +kubebuilder:validation:Optional
	LoadBalancerIDRef *v1.NamespacedReference `json:"loadBalancerIdRef,omitempty" tf:"-"`

	// Selector for a Balancer in loadbalancer to populate loadBalancerId.
	// +kubebuilder:validation:Optional
	LoadBalancerIDSelector *v1.NamespacedSelector `json:"loadBalancerIdSelector,omitempty" tf:"-"`

	// (Number) ID of the Network to attach the Load Balancer to. Using subnet_id is preferred. Required if subnet_id is not set. If subnet_id or ip are not set, the Load Balancer will be attached to the last subnet (ordered by ip_range).
	// ID of the Network to attach the Load Balancer to. Using `subnet_id` is preferred. Required if `subnet_id` is not set. If `subnet_id` or `ip` are not set, the Load Balancer will be attached to the last subnet (ordered by `ip_range`).
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkID *float64 `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) ID of the Subnet to attach the Load Balancer to. Required if network_id is not set.
	// ID of the Subnet to attach the Load Balancer to. Required if `network_id` is not set.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/network/v1alpha1.Subnet
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in network to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

// BalancerNetworkSpec defines the desired state of BalancerNetwork
type BalancerNetworkSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BalancerNetworkParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BalancerNetworkInitParameters `json:"initProvider,omitempty"`
}

// BalancerNetworkStatus defines the observed state of BalancerNetwork.
type BalancerNetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BalancerNetworkObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BalancerNetwork is the Schema for the BalancerNetworks API. Manage the attachment of a Load Balancer in a Network in the Hetzner Cloud.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,hetzner}
type BalancerNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BalancerNetworkSpec   `json:"spec"`
	Status            BalancerNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BalancerNetworkList contains a list of BalancerNetworks
type BalancerNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BalancerNetwork `json:"items"`
}

// Repository type metadata.
var (
	BalancerNetwork_Kind             = "BalancerNetwork"
	BalancerNetwork_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BalancerNetwork_Kind}.String()
	BalancerNetwork_KindAPIVersion   = BalancerNetwork_Kind + "." + CRDGroupVersion.String()
	BalancerNetwork_GroupVersionKind = CRDGroupVersion.WithKind(BalancerNetwork_Kind)
)

func init() {
	SchemeBuilder.Register(&BalancerNetwork{}, &BalancerNetworkList{})
}
